'$schema': 'https://git.drupalcode.org/project/drupal/-/raw/HEAD/core/assets/schemas/v1/metadata.schema.json'
name: 'Élément :: Vidéo produit'
status: stable
props:
  type: object
  properties:
    title:
      type: string
      title: Titre
    caption:
      type: string
      title: Légende
slots:
  image:
    title: Miniature (16:9)
  video:
    title: Vidéo (embed)
  description:
    title: Description
  actions:
    title: Lien
  download:
    title: Fichier à télécharger
libraryOverrides:
  dependencies:
    - drive_matic/video-facade
