drivematic_configurator.configuration:
  path: '/configurer'
  defaults:
    _form: '\Drupal\drivematic_configurator\Form\ConfigurationForm'
    _title: 'Configurez votre véhicule et obtenez votre tarif'
  requirements:
    _role: 'partenaire'

drivematic_configurator.quote:
  path: '/configurer/devis'
  defaults:
    _form: '\Drupal\drivematic_configurator\Form\QuoteForm'
    _title: 'Votre devis'
  requirements:
    _role: 'partenaire'
