services:
  drivematic_configurator.quote_calculator:
    class: Drupal\drivematic_configurator\Service\QuoteCalculator
    arguments:
      - '@entity_type.manager'
  drivematic_configurator.quote_reference_generator:
    class: Drupal\drivematic_configurator\Service\QuoteReferenceGenerator
    arguments:
      - '@entity_type.manager'
      - '@lock'
      - '@datetime.time'
  drivematic_configurator.quote_persister:
    class: Drupal\drivematic_configurator\Service\QuotePersister
    arguments:
      - '@entity_type.manager'
      - '@drivematic_configurator.quote_calculator'
      - '@drivematic_configurator.quote_reference_generator'
      - '@datetime.time'
