quantity_stepper:
  version: 1.x
  js:
    js/quantity-stepper.js: {}
  dependencies:
    - core/drupal
    - core/once

configurator_reveal:
  version: 1.x
  js:
    js/configurator-reveal.js: {}
  dependencies:
    - core/drupal
    - core/once
