'$schema': 'https://git.drupalcode.org/project/drupal/-/raw/HEAD/core/assets/schemas/v1/metadata.schema.json'
name: 'Bloc :: Caractéristiques produit'
status: stable
props:
  type: object
  properties:
    title:
      type: string
      title: Titre
    caption:
      type: string
      title: Légende de l’image
    downloads:
      type: array
      title: Documents à télécharger
      items:
        type: object
        properties:
          label:
            type: string
            title: Libellé du bouton
          url:
            type: string
            title: URL du fichier
          format:
            type: string
            title: Format (ex. PDF)
          size:
            type: string
            title: Poids formaté
slots:
  image:
    title: Image (sans crop)
  characteristics:
    title: Caractéristiques
